server:
  port: 8086
  
info:
  component: Products Core Service

logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: OFF
    org.springframework.cloud: OFF
    org.springframework.boot: OFF
    org.springframework: OFF

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/